baseApp/urls.py
from django.urls import path
from . import views

app_name = 'baseApp'

urlpatterns = [
   
]

categories/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from products import views as productViews


app_name = 'categories'

urlpatterns = [
    path('list/',views.CategoryList.as_view(),name='list'),
    path('new/',views.CreateCategoryView.as_view(),name='new'),
    path('<slug>/',productViews.ProductListView.as_view(),name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chemist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('baseApp/',include('baseApp.urls',namespace='baseApp')),
    path('categories/',include('categories.urls',namespace='categories')),
    path('products/',include('products.urls',namespace='products')),
]

templates/aside.html
{% load staticfiles %}

    <div class="row">
        <div class="col-md-12">
            <img src=" {% static 'chemist/images/aside1.jpg' %} " class="img-responsive right-block" alt="Content at aside number 1">
       
        </div>
        <div class="col-md-12">
            <img src=" {% static 'chemist/images/aside2.jpg' %} " class="img-responsive right-block" alt="Content at aside number 1">
       
        </div>
        <div class="col-md-12">
            <img src=" {% static 'chemist/images/aside3.jpg' %} " class="img-responsive right-block" alt="Content at aside number 1">
       
        </div>
        <div class="col-md-12">
            <img src=" {% static 'chemist/images/aside4.jpg' %} " class="img-responsive right-block" alt="Content at aside number 1">
        
        </div>
    </div>
   

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Star Social</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'chemist/css/main.css' %}">
    <script src="{% static 'bower_components/react/react.development.js' %}"></script>
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src=" {% static 'chemist/js/indexReact.jsx' %} "></script>
</head>
<body>
    <!-- Link to home page -->
    
    <nav class="navbar mynav" role="navigation" id="navbar">        
        <div class="container-fluid">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Welcome To Big Deal</a>
            <ul class="nav navbar-nav navbar-right mynavbar">
                <li><a href="" class="glyphicon glyphicon-search">Search</a></li>
                <li><a href=" {% url 'home' %} ">Home Page</a></li>                
                {% if user.is_authenticated %}                    
                    <li><a href="{% url 'categories:list' %} ">Categories</a></li>
                    <li><a href="">Products</a></li>
                    <li><a href="">Cart</a></li>
                    <li><a href=" {% url 'logout' %} ">Logout</a></li>
                    
                {% else %}
                    <li><a href="">Products</a></li>
                    <li><a href="">Cart</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="">Sign Up</a></li>
                {% endif %}

            </ul>

        </div>
      
    </nav>
    <div class="jumbotron bigdeal">
        <img id="navImage" class="img-responsive center-block" src=" {% static 'chemist/images/AmazoneNav.jpg' %} " alt="Nav Image">
    </div>
    <div class="container mycontent">
        <div class="row">
            <div class="col-md-8 two-div container-fluid">
                {% block content %}  
                <!-- include content here--> 
                {% endblock %}  
            </div>
            <!-- bootstrap for Aside -->
            <div class="col-md-4" id="asideBackGroundColor">
                {% block aside %}
                <!--include Aside here -->
                {% endblock %}
            </div>      
       
        
        </div>        
        
    </div>
    <div class="container-fluid myfooter">  
        <footer id="footer">
            <p>References: <a href="chemistwarehouse.com.au">Chemist Warehouse</a> 
                <a href="https://www.djangoproject.com">Django Ducumentation</a>            
            </p>
            <p>Copy right: Cuong Bui</p>    
        </footer>              
              
    </div>  
</body>
</html>

templates/content.html
{% load staticfiles %}

    <div class="row">   
        {% for imgPath in row1 %}   
        <span>jj{{imgPath}}</span>        
            <div class="col-md-6">               
                
                <img src="{% static imgPath %}" class="img-responsive center-block" alt="Image path problem">
        
            </div>
        {% endfor %} 
        <div id="testReact">
            <h2>
                This is the Test of homepage on React, go to <a href=" {% url 'categories:list' %} ">Category for products</a>
            </h2>
        </div>  
        <div>
            {% load render_bundle from webpack_loader %}
            <div id="react-app"></div>
            {% render_bundle 'main' %}
        </div>
    </div>  
    

templates/contentbackup.html
{% load staticfiles %}
<div class="col-md-8 two-div container-fluid">Main Content
    {% for i in range(0,4) %}
        
    {% endfor %}
    <div class="row">
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content11.png' %} " class="img-responsive center-block" alt="Content at Cell number 11">
        </div>
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content12.png' %} " class="img-responsive" alt="Content at Cell number 12">
       
        </div>                    
    </div>
    <div class="row">
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content21.png' %} " class="img-responsive center-block" alt="Content at Cell number 12">
       
        </div>
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content22.png' %} " class="img-responsive" alt="Content at Cell number 12">
       
        </div>                    
    </div>
    <div class="row">
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content31.png' %} " class="img-responsive center-block" alt="Content at Cell number 12">
       
        </div>
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content32.png' %} " class="img-responsive" alt="Content at Cell number 12">
       
        </div>                    
    </div>
    <div class="row">
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content41.png' %} " class="img-responsive center-block" alt="Content at Cell number 12">
       
        </div>
        <div class="col-md-6">
            <img src=" {% static 'chemist/images/content42.png' %} " class="img-responsive" alt="Content at Cell number 12">
       
        </div>                    
    </div>
</div> 

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}  
    {% include 'content.html' %}
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}

templates/test.html
{% extends 'index.html' %}

templates/thanks.html
{% extends 'index.html' %}