baseApp/urls.py
from django.urls import path
from . import views

app_name = 'baseApp'

urlpatterns = [
   
]

categories/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from products import views as productViews


app_name = 'categories'

urlpatterns = [
    path('list/',views.CategoryList.as_view(),name='list'),
    path('new/',views.CreateCategoryView.as_view(),name='new'),
    path('<slug>/',productViews.ProductListView.as_view(),name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chemist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('baseApp/',include('baseApp.urls',namespace='baseApp')),
    path('categories/',include('categories.urls',namespace='categories')),
    path('products/',include('products.urls',namespace='products')),
]

categories/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify   #for slug

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 255)
    slug = models.SlugField(allow_unicode = True, unique=True)
    description = models.CharField(max_length = 255)
    image = models.ImageField(upload_to = 'categories/images')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self,**kwargs):
        return reverse('categories:detail',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

categories/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name','description','image']
        widgets = {
            'name':forms.TextInput(),
            'description':forms.Textarea(),
            'image':forms.ClearableFileInput(),
        }

        

categories/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Category
from .forms import CategoryForm
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from products.models import Product

# Create class CreateView
class CreateCategoryView(LoginRequiredMixin, generic.CreateView):
    form_class = CategoryForm
    model = Category
    template_name = 'categories/category_form.html'
    redirect_field_name = 'categories/category_detail.html'
    

    

class CategoryDetail(generic.ListView):
    model = Category
    fields = ['name','slug']
    template_name = 'products/product_list.html'
    context_object_name = 'category'

     
class CategoryList(generic.ListView):
    model = Category
    template_name = 'categories/category_list.html'
    context_object_name = 'category_list'
    def get_context_data(self, **kwargs):
        #call super() to implement base context
        context = super().get_context_data(**kwargs)

        #now, adding extra data as wishing:
        #first, count number of objects displaying in template, divide by 2 (number of colmuns)
        allCategories = Category.objects.all()
        totalEntry = allCategories.count()
        if (totalEntry % 2) == 0:
            totalEntry = (totalEntry // 2)
        else:
            totalEntry = (totalEntry // 2) + 1
        
        #crate a two dimention list to contain objects
        
        listObjects = []
        for i in range(totalEntry): #number of rows displaying in template
            rowEntries = []
            for j in range(2):  #each row contain 2 entries or 2 columns
                try:
                    if allCategories[2*i+j]:
                        rowEntries.append(allCategories[2*i+j])
                    else:
                        pass
                except:
                    pass
            listObjects.append(rowEntries)     
        #pass the list to the context     
        context['listObjects'] = listObjects
        return context


    

categories/templates/categories/categories_base.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}  
    {% include 'content.html' %}
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}

categories/templates/categories/category_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}
    <h1>This is the page displaying products of the same type</h1>
    <h2>
        Name: {{category.name|safe}}        
    </h2>
    <h2>
        Slug String: {{category.slug}}        
    </h2>
    
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}

categories/templates/categories/category_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h4>Create New Category</h4>
    <form id="categoryForm" method="POST" action=" {% url 'categories:new' %} " enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create new Category" class="btn btn-primary btn-large">
        
    </form>
{% endblock %}

categories/templates/categories/category_list.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}  
    {% for rowEntry in listObjects %}
        <div class="row">   
            {% for eachEntry in rowEntry %}
                <a href=" {% url 'categories:detail' slug=eachEntry.slug %} ">
                    <!-- Note the way to get slug and put in the page -->
                    <div class="col-md-6">            
                        <h1>{{ eachEntry.name|safe }}</h1>                                
                        <div class="row">                   
                            <div class="col-sm-4">
                                <h4>{{eachEntry.description|safe}}</h4>
                            </div>
                            <div class="col-sm-8">                        
                                {% with 'media/'|add:eachEntry.image.name as imgPath %}                          
                                <img src="{% static imgPath %}" class="img-responsive center-block" alt="Content at Cell number 11">
                                {% endwith %}
                            </div>                
                        </div>           
                    </div>
                </a>      
            {% endfor %}   
        </div>  
    {% endfor %}
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}