baseApp/urls.py
from django.urls import path
from . import views

app_name = 'baseApp'

urlpatterns = [
   
]

chemist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('baseApp/',include('baseApp.urls',namespace='baseApp')),
    path('categories/',include('categories.urls',namespace='categories')),
    path('products/',include('products.urls',namespace='products')),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('new/',views.CreateProductView.as_view(),name='new'),
    path('detail/<slug>/',views.ProductDetailView.as_view(),name='detail'),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify   #for slug
from categories.models import Category
# Create your models here.
class Product(models.Model):
    productId = models.IntegerField(primary_key=True,null = False, unique=True)
    name = models.CharField(max_length = 255, unique=True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    savePrice = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    currentPrice = models.DecimalField(max_digits=7, decimal_places=2) 
    imagePath = models.ImageField(default='No_imange_yet')       
    updateDate = models.DateField(default = '2018-1-20')
    category = models.ForeignKey(Category,related_name="product",on_delete=models.CASCADE)
    #priceRecord = models.ForeignKey(PriceRecord, related_name='product',on_delete=models.CASCADE, blank = True)
    #Note that, ralated_name is used to query up in the relationship
    #such as, myCategory = Category.objects.filter(productType__productId=40022)
    

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self,**kwargs):
        return reverse('products:detail',kwargs = {'slug':self.slug})

    def discount(self):  #return value as%
        theDiscount = self.savePrice/(self.currentPrice + self.savePrice)
        return theDiscount

    class Meta:
        ordering = ['name'] 

class PriceRecord(models.Model):
    updateDate = models.DateField(default = '2018-1-20')
    savePrice = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    currentPrice = models.DecimalField(max_digits=7, decimal_places=2, default = 0) 
    
    def __str__(self):
        return self.updateDate

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

products/views.py
from .models import Product
from categories.models import Category
from django.shortcuts import render,get_object_or_404, redirect
#from .forms import CategoryForm
from django.views import generic
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render
from django.db.models import Count
from math import *

# Create your views here.
class CreateProductView(LoginRequiredMixin, generic.CreateView):
    model = Product
    template_name = 'products/product_form.html'
    redirect_field_name = 'categories/category_detail.html'
    fields = ['productId','name','currentPrice','savePrice','imagePath','updateDate','category']

class ProductListView(generic.ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'product_list'
    select_related = ('category')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(category__slug__iexact = self.kwargs.get('slug'))
    #override the get_context_data to add extra data to the templates
    #the purpose is to simplify the html structure
    def get_context_data(self, **kwargs):
        
        #call super() to implement base context
        context = super().get_context_data(**kwargs)

        #now, adding extra data as wishing:
        #first, count number of objects displaying in template, divide by 2 (number of colmuns)
        totalEntry = Product.objects.filter(category__slug__iexact = self.kwargs.get('slug')).count()
        if (totalEntry % 2) == 0:
            totalEntry = (totalEntry // 2)
        else:
            totalEntry = (totalEntry // 2) + 1
        
        #crate a two dimention list to contain objects
        allProducts = list(Product.objects.filter(category__slug__iexact = self.kwargs.get('slug')).all())
        listObjects = []
        for i in range(totalEntry):
            rowEntries = []
            for j in range(2):
                try:
                    if allProducts[2*i+j]:   
                        if allProducts[2*i+j].discount() > 0.2:                   
                            rowEntries.append(allProducts[2*i+j])
                    else:
                        pass
                except:
                    pass
            listObjects.append(rowEntries)     
        #pass the list to the context     
        context['listObjects'] = listObjects
        return context
        


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        
        #call super() to implement base context (object)
        context = super().get_context_data(**kwargs)

        #, then add extra context to the above context
        context['testContext'] = 'This is the test of additional context'
        return context

    

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}       
    <div class="row">        
        <h1>{{testContext}} </h1>           
        <!-- Note the way to get slug and put in the page -->
        <div class="col-md-6">                    
            <h3>{{ product.name|safe }}</h3>                                
            
            <h4>Price: {{product.currentPrice|safe}}</h4>
            <h4>Save: {{product.savePrice|safe}}</h4> 
            <h3>Shop now</h3>                           
        </div>
        <div class="col-md-6">                        
            {% with 'media/'|add:product.imagePath.name as imgPath %}                          
            <img src="{% static imgPath %}" class="img-responsive center-block" alt="Content at Cell number 11">
            {% endwith %}
        </div>              
    </div>
       
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}

products/templates/products/product_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
    <h4>Create New Product</h4>
    <form id="productForm" method="POST" action=" {% url 'products:new' %} " enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create new Product" class="btn btn-primary btn-large">
        
    </form>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}  
<h3>Big discount on following products, minimum 20%</h3>
    {% for rowEntry in listObjects %}     
    <div class="row">        
        {% for eachEntry in rowEntry %}
            <a href=" {% url 'products:detail' slug=eachEntry.slug %} ">
                <!-- Note the way to get slug and put in the page -->                
                <div class="col-md-6">                    
                    <h3>{{ eachEntry.name|safe }}</h3>                                
                    <div class="row">                   
                        <div class="col-sm-6">
                            <h4>Price: {{eachEntry.currentPrice|safe}}</h4>
                            <h4>Save: {{eachEntry.savePrice|safe}}</h4> 
                            <h3>Shop now</h3>                           
                        </div>
                        <div class="col-sm-6">                        
                            {% with 'media/'|add:eachEntry.imagePath.name as imgPath %}                          
                            <img src="{% static imgPath %}" class="img-responsive center-block" alt="Content at Cell number 11">
                            {% endwith %}
                        </div>                
                    </div>           
                    
                    
                </div>
            </a>        
        {% endfor %}
    </div>
    {% endfor %}
       
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}

products/templates/products/product_list_backup.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Main content start from here-->
{% block content %}       
    <div class="row">
        <h2>Rows: {{contentRow}} </h2>
        <h2>Columns: {{contentCol}} </h2>
        <h2> {{product_list[2].name}} </h2>
        {% for product in product_list %}
            <a href=" {% url 'products:detail' slug=product.slug %} ">
                <!-- Note the way to get slug and put in the page -->
                <div class="col-md-6">                    
                    <h3>{{ product.name|safe }}</h3>                                
                    <div class="row">                   
                        <div class="col-sm-6">
                            <h4>Price: {{product.currentPrice|safe}}</h4>
                            <h4>Save: {{product.savePrice|safe}}</h4> 
                            <h3>Shop now</h3>                           
                        </div>
                        <div class="col-sm-6">                        
                            {% with 'media/'|add:product.imagePath.name as imgPath %}                          
                            <img src="{% static imgPath %}" class="img-responsive center-block" alt="Content at Cell number 11">
                            {% endwith %}
                        </div>                
                    </div>           
                    
                    
                </div>
            </a>        
        {% endfor %}
    </div>
       
{% endblock %}  

{% block aside %}
    {% include 'aside.html' %}
{% endblock %}